on:
    push:
        branches:
            - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint
        id: lint
        uses: sunnysid3up/python-linter@master